services:
  
  pgdb:
    container_name: my_postgres
    image: postgres:17.3-alpine3.21
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - /home/sergey/Документы/SQL/db_pg:/var/lib/postgresql/data
    env_file:
      - .env